export QT_QPA_EGLFS_ALWAYS_SET_MODE=1
export QT_QPA_PLATFORM=eglfs
export QT_QPA_EGLFS_HIDECURSOR=1
export XDG_RUNTIME_DIR=/run/user/1000
export LIBINPUT_CALIBRATION_MATRIX="0 -1 1 1 0 0"

# export QT_QPA_EGLFS_WIDTH=1280
# export QT_QPA_EGLFS_HEIGHT=800

# export QT_QPA_EGLFS_PHYSICAL_WIDTH=150.72
# export QT_QPA_EGLFS_PHYSICAL_HEIGHT=94.2

#XDG_RUNTIME_DIR=/run/user/1000 weston --tty 2

/home/pi/build/Car_Audio
